### ISSUE TITLE
[rule proposal] Geographically separate reward pool

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/slingshot#428]
Phase 2.3 gonna remove the limit of self-dealing, making it essentially a competition of miners - it will be very similar to space race. I propose separate reward pool like spacerace so that people outside of Asia continent can have a chance to participate.

**Comment by KaptinLin** [comment]
We don't know where slingshotter comes from. There is no verification mechanism such as ip to verify them.

**Comment by kernelogic** [comment]
Provide personal ID or company ID to demonstrate where you are from. a KYC.

**Comment by vht210** [comment]
I also don't agree with separate geographically rewards pool. Yes data distributed globally to have higher score is better choice

**Comment by kernelogic** [comment]
Really? If you look at the deals from the top 10 projects, they are centralized in China.

**Comment by vht210** [comment]
I think even top 20, but still you can not just divide based on the current situation/result..need to have better justification.

**Comment by pooja** [comment]
Hey folks, thanks for submitting this rule proposal. As we learned from Space Race 1, there isn't a great way to verify geographic location of a participant. IPs are easy to spoof, and having to validate other information such as company registration information is also not 100% reliable (relatively easy to forge documents) and creates an unreasonable overhead burden on Slingshot admins. And lastly, participants can always spin up nodes in other regions in order to get around this rule -- as has happened in other competitions. So this probably won't work to accomplish what you would like it to accomplish. 

I think there are other ways to limit the rewards going to one particular geographic region, e.g. limiting the amount of rewards that can go to any one team or project. We'd prefer to lean into those rules instead. We'll be closing out this issue, but feel free to follow the conversation on other issues, e.g. https://github.com/filecoin-project/slingshot/issues/429
