### ISSUE TITLE
[rule proposal] Extra bonus for adding UI and API

### ISSUE THREAD

**Issue by vht210** [filecoin-project/slingshot#430]
## Problem
Most of data once retrieving will be difficult to use if there are no example or showcase. 

## Proposed Solution
Give extra bonus (rewards*1.1) for people/team who take extra effort to present the data on UI and API.
Also team will spend more time on preprocessing data more usable.

**Comment by xinaxu** [comment]
One hard problem is whether the reward should depend on the quality of the UI/API design. You can have an easy UI just to display the slingshot csv as a table in static HTML.
I would change this proposal to provide a flat bonus for UI/API since the effort needed is regardless of the deals stored.

**Comment by pooja** [comment]
This is a great suggestion, and actually one that should be a requirement for all teams. It's necessary to maintain a searchable UI with the relevant information in order for the data to actually be usable since the Slingshot website is not intended to be the long-term index for data that has been stored.

**Comment by pooja** [comment]
We'll close this issue for now, since we'll be implementing a version of this for Slingshot 2.3 judging for all teams
