### ISSUE TITLE
[dataset request] App Install Lab

### ISSUE THREAD

**Issue by xunlei-filebox** [filecoin-project/slingshot#449]
## Dataset being requested
Dataset Name: App Install Lab
Dataset Description: A file library containing various application installation packages.
Size: -
File Format: Various
Link to Dataset: https://www.xunlei.com/

**Comment by dkkapur** [comment]
@xunlei-filebox - thanks for submitting this dataset to be added to Slingshot. 

A few questions: 

- could you share any details on the set of application installation packages that are included in the file library? 
- can you confirm that the button in the image below downloads the dataset and it is usable/extract-able by anyone? 
- do you happen to have a versions of this site in different languages as well? (not necessarily a requirement, just figured I'd check since it would reduce the questions I'll probably have for you)

![image](https://user-images.githubusercontent.com/2343218/117399436-69aa1580-aeb5-11eb-8ebf-d8e33da9a815.png)

**Comment by dkkapur** [comment]
@xunlei-filebox - just wanted to circle back on this and see if you had had the chance to review the above comment?

**Comment by dkkapur** [comment]
Closing this out for now. Please open a new issue in this repo if you'd like to propose this or a different dataset for Slingshot.
