### ISSUE TITLE
[dataset request] Azure Open Datasets

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/slingshot#464]
Request to add large datasets listed in Azure Open Datasets
https://docs.microsoft.com/en-us/azure/open-datasets/dataset-catalog

## Dataset to be added to Slingshot
| Dataset Name                | Dataset Description                                                                                                           | Size  | File Format | Link to Dataset download                                                                         |
|-----------------------------|-------------------------------------------------------------------------------------------------------------------------------|-------|-------------|--------------------------------------------------------------------------------------------------|
| TartanAir AirSim            | TartanAir: AirSim simulation dataset for simultaneous localization and mapping (SLAM)                                         | 3TB   | PNG,NPY,TXT | https://docs.microsoft.com/en-us/azure/open-datasets/dataset-tartanair-simulation                |
| SnpEff                      | SnpEff: Genomic variant annotations and functional effect prediction toolbox                                                  | 2TB   | ZIP         | https://docs.microsoft.com/en-us/azure/open-datasets/dataset-snpeff                              |
| 1000 Genomes                | The 1000 Genomes Project ran between 2008 and 2015, creating the largest public catalog of human variation and genotype data. | 815TB |             | https://docs.microsoft.com/en-us/azure/open-datasets/dataset-1000-genomes                        |
| GATK Resource Bundle        | The GATK resource bundle is a collection of standard files for working with human resequencing data with the GATK.            | 6TB   |             | https://docs.microsoft.com/en-us/azure/open-datasets/dataset-gatk-resource-bundle                |
| Russian Open Speech To Text | A collection of speech samples derived from various audio sources. The dataset contains short audio clips in Russian.         | 3TB   |             | https://docs.microsoft.com/en-us/azure/open-datasets/dataset-open-speech-text?tabs=azure-storage |

**Comment by xinaxu** [comment]
@dkkapur Hey got some time to take a look?

**Comment by dkkapur** [comment]
@xinaxu - quick thoughts:
* TartanAir AirSim - looks good, happy to add this one
* SnpEff - same as above ^
* 1000 Genomes - have a lot of genome datasets already, similar to this one, might be worth skipping this for the time being, especially since its rather large and we're likely in the final stages of v2 Slingshot
* GATK Resource Bundle - per https://gatk.broadinstitute.org/hc/en-us/articles/360035890811-Resource-bundle looks like the latest / more usable version is actually hosted on GCloud Bucket; do you think we should use that instead? 
* Russian Open Speech To Text - looks good, we have other text-to-speech datasets as well but AFAIK no good complete uploads for Russian

Would you still like to proceed with 3/5 of these and potentially upload in 2.7? Happy to approve and adjust in the next days if so. 

Thanks

**Comment by xinaxu** [comment]
@dkkapur Thanks. I've created a pull request for the 3 out of 5.

**Comment by dkkapur** [comment]
@orvn @timelytree - https://github.com/filecoin-project/slingshot/pull/468 was merged, can we add these to the list of eligible datasets for projects on the site? Thank you!

**Comment by orvn** [comment]
No problem @dkkapur

**Comment by orvn** [comment]
These (3) new datasets are now available in the production Slingshot site for phase `2.7`: 
- `snpeff`
- `russian-open-speech-to-text`
- `tartanair`
